# Generated by Django 4.2.7 on 2025-10-17 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='disciplinas_requeridas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='users.disciplina', verbose_name='Disciplinas Requeridas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='habilidades_requeridas',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='users.habilidad', verbose_name='Habilidades Requeridas'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='colaboracion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to='projects.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='colaboracion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='colaboracion',
            unique_together={('proyecto', 'usuario')},
        ),
    ]
